# Generated by Django 5.0.2 on 2024-04-27 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_users_options_alter_users_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='users',
            name='start_time',
        ),
    ]
