# Generated by Django 5.0.2 on 2024-05-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_faceid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaceID',
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
