# Generated by Django 5.0.2 on 2024-05-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='image',
            field=models.ImageField(default=1, upload_to='users/photo'),
            preserve_default=False,
        ),
    ]
