# Generated by Django 5.0.2 on 2024-05-03 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_employees_image_alter_employees_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
