# Generated by Django 5.0.2 on 2024-06-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_kelish_user_ketish_user_alter_ketish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ketish',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
